---
title: "04f_fig5"
author: "Yongxuan Guo"
date: '2022-10-28'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## set work directory and load packages
```{r}
if (!require("pacman")){
  install.packages("pacman")
}
require(pacman)
pacman::p_load(raster, sf, scales, ggplot2, data.table, trend, patchwork)

# tmpdir path can be changed to your own temp file path
raster::rasterOptions(tmpdir = '/project/public/')

# idir points to where you save the project
idir <- "~/wildfire/WUI/GlobalWUI/"
wgs84 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
```

## landcover time series: based on HILDA+ long term data
```{r}
# load data
lulc <- fread(paste0(idir, "Data/fig1/HILDA+_change_2000-2019.csv"))
lulc$x <- as.integer(lulc$year) - 1999

# trend detection
mk.test(lulc$urban)
mk.test(lulc$wildland)

# draw
lm_u <- lm(formula = urban/urban[1] ~ x, data = lulc)
ci_u <- confint(lm_u, 'x', 0.95)
format(lm_u$coefficients[2]*100, digits=2)
format((lm_u$coefficients[2]-ci_u[1])*100, digits = 1)
lm_w <- lm(formula = wildland/wildland[1] ~ x, data = lulc)
ci_w <- confint(lm_w, 'x', 0.95)
format(lm_w$coefficients[2]*100, digits=2)
format((lm_w$coefficients[2]-ci_w[1])*100, digits = 1)

p_lu <- ggplot(lulc) +
  geom_line(aes(x = x, y = urban/100000, group = 1), color = '#993404', alpha = 0.8, linewidth = 0.4) +
  geom_line(aes(x = x, y = wildland/32/100000, group = 1), color =  '#74c476', alpha = 0.8, linewidth = 0.4) +
  geom_smooth(aes(x = x, y = urban/100000, group = 1), color = '#993404', method = lm, linetype = 'dashed', fill = '#993404', linewidth = 0.6) +
  geom_smooth(aes(x = x, y = wildland/32/100000, group = 1), color =  '#74c476', method = lm, linetype = 'dashed', fill = '#c7e9c0', linewidth = 0.6) +
  theme_bw() +
  annotate("text", 14, 16.4, label = expression(Urban ~ area  ~ 0.72 %+-% '0.05% year' ^ {-1}), color = '#993404', size = 2) +
  annotate("text", 10, 18.5, label = expression(Wildland ~ area  ~ 0.05 %+-% '0.02% year' ^ {-1}), color = '#74c476', size = 2) +
  scale_y_continuous(expand = c(0,0), labels = comma, n.breaks = 5, limits = c(16,19),
                     name = expression(Urban %*% 10 ^ {6} ~ km ^ {2}), 
                     sec.axis = sec_axis(~.*32, name = expression(Wildland %*% 10 ^ {6} ~ km ^ {2}), labels = comma)) +
  scale_x_continuous(limits = c(1, 21), breaks = c(1, 11, 21), labels = c('2000', '2010', '2020')) +
  theme(aspect.ratio = 0.8,
        axis.title.y.left = element_text(color = '#993404', size = 7),
        axis.title.y.right = element_text(color = '#74c476', size = 7, angle = 90),
        axis.text.y.left = element_text(color = '#993404', size = 6, angle = 90, hjust = 0.5),
        axis.text.y.right = element_text(color = '#74c476', size = 6, angle = 90, hjust = 0.5),
        axis.text.x = element_text(size = 7),
        axis.line.y.left = element_line(color = '#993404'),
        axis.line.y.right = element_line(color = '#74c476'),
        axis.ticks.y.left = element_line(color = '#993404'),
        axis.ticks.y.right = element_line(color = '#74c476'),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.3),
        plot.title = element_text(hjust = 0.5),
        title = element_text(size = 7),
        axis.title.x = element_blank(),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
  )
```

## fire time series
```{r}
# load fire data
fire <- fread(paste0(idir, "Data/fig1/MODIS_fire_2003-2020.csv"))

# trend detection
mk.test(fire$frp)
mk.test(fire$count)

# draw
lm_c <- lm(formula = count/count[1] ~ x, data = fire)
ci_c <- confint(lm_c, 'x', 0.95)
format(lm_c$coefficients[2]*100, digits=2)
format((lm_c$coefficients[2]-ci_c[1])*100, digits = 1)
lm_f <- lm(formula = frp/frp[1] ~ x, data = fire)
ci_f <- confint(lm_f, 'x', 0.95)
format(lm_f$coefficients[2]*100, digits=2)
format((lm_f$coefficients[2]-ci_f[1])*100, digits = 1)

p_f <- ggplot(fire) +
  geom_line(aes(x = x, y = count/100000, group = 1), color = "#66c2a5", alpha = 0.8, linewidth = 0.4) +
  geom_line(aes(x = x, y = frp/40/100000, group = 1), color =  "#fc8d62", alpha = 0.8, linewidth = 0.4) +
  geom_smooth(aes(x = x, y = count/100000, group = 1), color = "#66c2a5", method = lm, linetype = 'dashed', fill = '#e5f5e0', linewidth = 0.6) +
  geom_smooth(aes(x = x, y = frp/40/100000, group = 1), color =  "#fc8d62", method = lm, linetype = 'dashed', fill = '#fee0d2', linewidth = 0.6) +
  theme_bw() +
  annotate("text", 10, 41.8, label = expression('Fire count -0.87' %+-% '0.39% year' ^ {-1}), color = "#66c2a5", size = 2) +
  annotate("text", 16, 58, label = expression('FRP -1.01' %+-% '0.56% year' ^ {-1}), color = "#fc8d62", size = 2) +
  scale_y_continuous(labels = comma, n.breaks = 5, 
                     name = expression('Fire count ('%*% 10 ^ {5} ~')'), 
                     sec.axis = sec_axis(~.*40, name = expression(sum(FRP) ~ '('%*% 10 ^ {5} ~'MW)'), labels = comma)) +
  geom_vline(xintercept = 4, color = '#636363', linetype = 'dashed', linewidth = 0.2) +
  scale_x_continuous(limits = c(1, 21), breaks = c(1, 4, 11, 21), labels = c('2000', '2003', '2010', '2020')) +
  theme(aspect.ratio = 0.8,
        axis.title.y.left = element_text(color = "#66c2a5", size = 7),
        axis.title.y.right = element_text(color = "#fc8d62", size = 7, angle = 90),
        axis.text.y.left = element_text(color = "#66c2a5", size = 6, angle = 90, hjust = 0.5),
        axis.text.y.right = element_text(color = "#fc8d62", size = 6, angle = 90, hjust = 0.5),
        axis.line.y.left = element_line(color = "#66c2a5"),
        axis.line.y.right = element_line(color = "#fc8d62"),
        axis.ticks.y.left = element_line(color = "#66c2a5"),
        axis.ticks.y.right = element_line(color = "#fc8d62"),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.3),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 7),
        plot.title = element_text(hjust = 0.5),
        title = element_text(size = 7),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
  )
```


```{r}
# load data
era5 <- fread(paste0(idir, "Data/fig1/ERA5_maxT_FWI_2000-2020.csv"))

# trend detection
mk.test(era5$fwi)
mk.test(era5$maxTemp)

# draw
lm_f <- lm(formula = fwi/fwi[1] ~ x, data = era5)
ci_f <- confint(lm_f, 'x', 0.95)
format(lm_f$coefficients[2]*100, digits=2)
format((lm_f$coefficients[2]-ci_f[1])*100, digits = 2)
lm_t <- lm(formula = maxTemp/maxTemp[1] ~ x, data = era5)
ci_t <- confint(lm_t, 'x', 0.95)
format(lm_t$coefficients[2]*100, digits=2)
format((lm_t$coefficients[2]-ci_t[1])*100, digits = 2)

p_fr <- ggplot(era5) +
  geom_line(aes(x = x, y = fwi), color = '#54278f', alpha = 0.8, linewidth = 0.4) +
  geom_smooth(aes(x = x, y = fwi, group = 1), color = '#54278f', method = lm, linetype = 'dashed', fill = '#dadaeb', linewidth = 0.6) +
  geom_line(aes(x = x, y = maxTemp*1.1), color = '#cb181d', alpha = 0.8, linewidth = 0.4) +
  geom_smooth(aes(x = x, y = maxTemp*1.1, group = 1), color = '#cb181d', method = lm, linetype = 'dashed', fill = '#fee0d2', linewidth = 0.6) +
  theme_bw()  +
  annotate("text", 8, 16.9, label = expression(FWI ~ 0.28 %+-% '0.14% year' ^ {-1}), color = '#54278f', size = 2) +
  annotate("text", 12.2, 14.8, label = expression(Max ~ temperature ~ 0.35 %+-% '0.11% year' ^ {-1}), color = '#cb181d', size = 2) +
  scale_y_continuous(expand = c(0,0), labels = comma, n.breaks = 5, 
                     name = 'Fire Weather Index',
                     sec.axis = sec_axis(~./1.1, name = 'Max temperature (°C)', labels = comma)) +
  scale_x_continuous(limits = c(1, 21), breaks = c(1, 11, 21), labels = c('2000', '2010', '2020')) +
  theme(aspect.ratio = 0.8,
        axis.title.y.left = element_text(color = '#54278f', size = 7),
        axis.title.y.right = element_text(color = "#cb181d", size = 7, angle = 90),
        axis.text.y.left = element_text(color = '#54278f', size = 6, angle = 90, hjust = 0.5),
        axis.text.y.right = element_text(color = "#cb181d", size = 6, angle = 90, hjust = 0.5),
        axis.line.y.left = element_line(color = "#54278f"),
        axis.ticks.y.left = element_line(color = "#54278f"),
        axis.line.y.right = element_line(color = "#cb181d"),
        axis.ticks.y.right = element_line(color = "#cb181d"),
        axis.line = element_line(linewidth = 0.2),
        axis.ticks = element_line(linewidth = 0.3),
        axis.title.x = element_blank(),
        axis.text.x = element_text(size = 7),
        plot.title = element_text(hjust = 0.5),
        title = element_text(size = 7),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank()
  ) 
```

```{r}
fig1 <- p_fr + p_f + p_lu + plot_layout(nrow = 1)
odir <- paste0(idir, "Figure")
ggsave(plot = fig1,
       filename = "fig1_static.pdf",
       device = "pdf", path = odir,
       width = 180, height = 70, units = "mm",
       dpi = 320)
```
