---
title: "04b_fig3"
author: "Yongxuan Guo"
date: "2022/6/4"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# fig3. Global WUI change percentage from 2000 to 2020, zoom in area shows how WUI change in detail.
## set work directory and load packages
```{r}
if (!require("pacman")){
  install.packages("pacman")
}
require(pacman)
pacman::p_load(raster, sf, scales, ggplot2, dplyr, ggnewscale, ggmap, ggrepel, ggpubr, patchwork)

raster::rasterOptions(tmpdir = '/project/public/')

idir <- "~/wildfire/WUI/GlobalWUI/"
wgs84 <- CRS("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
```

## read 1km WUI
```{r}
wd <- paste0(idir, 'Data/')
files <- dir(path = wd, pattern = glob2rx('*rmNA_*.tif'))
rList <- NULL
WUI_area <- NULL
for(i in 1:length(files)){
  rList[[i]] <- raster(paste0(wd, files[i]))
}
crs <- crs(rList[[3]])
```

## draw global change between 2000 and 2020 (0.1°)
### prepare change data
```{r}
odir <- "~/wildfire/WUI/GlobalWUI/Data/fig3"
delta <- raster(paste0(odir, "delta_20-00.tif"))

# 0.1°version
delta <- aggregate(delta, fact = c(10, 10))
delta[delta == 0] <- NA
df <- as.data.frame(delta, xy=T)
names(df) <- c('x', 'y', 'delta')
# d <- filter(df, !is.na(delta))
# natural_breaks(12, d["delta"])
my_at <- c(-1, -0.05, -0.03, -0.01, -0.005, 0.005, 0.01, 0.03, 0.05, 0.1, 0.3, 1)
df$valueDiscr <- cut(df$delta,
                     breaks = my_at, right = T)
```

### ocean bottom data
```{r}
# read original data
bath <- readRDS(paste0(idir, "Data/ocean_bottom.rds"))

# crop and resample data to align main result
bath2 <- crop(bath, delta)
bath3 <- resample(bath2, delta)

# remove terrestrial data
bath3[bath3 > 0] <- NA

# get dataframe
df_b <- as.data.frame(bath3, xy = T)
```

### main plot
```{r}
# zoomin area annotation
points <-cbind(x = c(-82, 27.5, 114), y = c(36, -26, 22.75)) %>%
  as.data.frame()

# green-pink-purple
cols1 <- rev(c(rev(c('#fcc5c0','#fa9fb5','#f768a1','#dd3497','#ae017e','#7a0177')),'transparent','#a1d99b','#74c476','#31a354','#006d2c'))

world <- filter(spData::world, region_un!="Antarctica")
world <- st_transform(world, crs = crs(delta))
p <- ggplot() +
  geom_raster(data = df_b, mapping = aes(x = x, y = y, fill = Blue.Earth.Bathymetry)) +
  scale_fill_gradient(low = "#21ADE3", high = "#f7fbff", na.value = "transparent", guide = 'none', limits = c(-12000,0)) +
  geom_sf(data = world, fill = '#252525', color = NA) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  new_scale_fill() +
  geom_raster(data = df, aes(x = x, y = y,fill = valueDiscr)) +
  theme_classic() +
  scale_fill_manual(values = cols1, na.translate = F, 
                    labels = c('    ', '  -5', '  -3','  -1', '-0.5', ' 0.5', '   1', '   3', '   5', '  10', '   30', ''),                 
                    guide = guide_legend(nrow = 1, 
                                         keywidth = 0.6, keyheight = 0.8,
                                         label.position = "bottom", title.position = "top",
                                         title = expression(Delta(WUI)~'(%)'),
                                         title.hjust = 0.5,
                                         label.hjust = -4)) +
  geom_sf(data = world, fill = NA, linewidth = 0.05, color = "#969696", alpha = 0.5) +
  geom_point(data = points, aes(x=x,y=y), color = 'black', fill = '#addd8e', stroke = 0.5, shape = 21, size = 1) +
  theme(legend.position = c(0.6,0.12),
        legend.direction = 'horizontal',
        legend.spacing.x = unit(0, 'cm'),
        legend.background = element_blank(), 
        legend.title = element_text(size = 10),
        panel.border = element_blank(),
        legend.margin=margin(0,0,0,0),
        legend.box.margin=margin(0,0,0,0),
        legend.text = element_text(color = "black", size = 10),
        axis.text.x  = element_blank(),
        axis.text.y  = element_blank(),
        axis.line = element_blank(),
        axis.ticks = element_blank(),
        plot.title = element_text(hjust = 0.1, vjust = -5), 
        plot.margin= grid::unit(c(0, 0.2, 0.5, 0), "in")) +
  labs(x ="", y = "") 

odir <-paste0(idir, "Figure")
ggsave(plot = p,
       filename = "fig3_20-00_0.1.pdf",
       device = "pdf", path = odir,
       width = 7, height = 5, units = "in",
       dpi = 320)

```

### draw local change (ggmap basemap)
```{r}
# set color
LCcodes <- c(1:7, 10)
LCnames <-c("2000", "2010", "2020", "00_10", "00_20", "10_20", "001020","Wildland")
LCcolors <- c(rgb(101,212,240,maxColorValue = 255),
              rgb(255,236,161,maxColorValue = 255),
              rgb(255,135,143,maxColorValue = 255),
              rgb(82,171,82,maxColorValue = 255),
              rgb(220,128,255,maxColorValue = 255),
              rgb(255,190,99,maxColorValue = 255),
              rgb(255,244,38,maxColorValue = 255),
              "transparent")
names(LCcolors) <- as.character(LCcodes)

# east America extent(-82.5, -82.3, 36, 36.5)
i <- 130
twd <- paste0(idir, "/Data/fig3/temp", i)

# drawing
w <- raster(paste0(twd, "/Origin_00.tif"))
w[w < 20 | w > 40] <- 0
w[w != 0] <- 1

W_00 <- raster(paste0(twd, "/WUI_00.tif"))
W_10 <- raster(paste0(twd, "/WUI_10.tif"))
W_20 <- raster(paste0(twd, "/WUI_20.tif"))
delta <- 4*W_20 + 2*W_10 + W_00
c <- delta - 10 * w
d <- c
d[c==0] <- NA
d[c==-10] <- 10
d[c==1|c==-9] <- 1
d[c==2|c==-8] <- 2
d[c==4|c==-6] <- 3
d[c==3|c==-7] <- 4
d[c==5|c==-5] <- 5
d[c==6|c==-4] <- 6
d[c==7|c==-3] <- 7
dc <- crop(d, extent(-82.5, -82.3, 36.3, 36.4))
df_d <- as.data.frame(dc, xy = T)
names(df_d) <- c("x", "y", "LC")

# set key to get base map
register_stadiamaps(key = '282b7619-39e7-40b1-9d4d-1388c05bdeb3')

myLocation <- c(-82.5, 36.3, -82.3, 36.4)
myMap <- get_stadiamap(bbox = myLocation, zoom = 13, maptype = "stamen_terrain_background", crop = FALSE)
city <- cbind(36.315234726641776, -82.35369304325661, 'Johnson City') %>%
  as.data.frame()
names(city) <- c('y', 'x', 'name')
city$x <- as.double(city$x)
city$y <- as.double(city$y)

p1 <- ggmap(myMap) +
    geom_point(data = df_d, aes(x = x, y = y, color = as.character(LC)), size = 0.5) +
    geom_point(data = city, mapping = aes(x = x, y = y), color = 'black', fill = 'red', shape = 21, size = 1, stroke = 0.5) + 
    geom_text_repel(data = city, mapping = aes(x = x, y = y, label = name), color = 'white', size = 3, bg.color = "black", nudge_y = 0.007, nudge_x = 0.001) +
    scale_color_manual(name = "",
                       values = LCcolors,
                       labels = LCnames,
                       na.translate = FALSE,
                       guide = 'none') +
    theme_bw() +
    theme(
        plot.background = element_rect(color = "transparent", fill ="transparent"),
        plot.margin = margin(2,2,2,2),
        legend.background = element_rect(color = "transparent", fill ="transparent"),
        axis.text = element_text(size = 6), 
        axis.text.y = element_text(angle = 90, hjust = 0.5)) +
    scale_x_continuous(expand = c(0,0), breaks = c(-82.45, -82.35), label = c('82.45°W', '82.35°W'), limits = c(-82.5, -82.4)) +
    scale_y_continuous(expand = c(0,0), breaks = c(36.32, 36.37), label = c('36.32°N', '36.37°N'), limits = c(36.3, 36.4)) +
    labs(x ="", y = "", fill = '') +
    geom_rect(aes(xmin = -82.5, xmax = -82.3, ymin = 36.3, ymax = 36.4), color = "black", inherit.aes = FALSE, fill = "transparent") + 
    guides(fill = "none")


# South Africa extent(27.2, 27.4, -25.7, -25.6)
i <- 726
twd <- paste0(idir, "/Data/fig3/temp", i)

# drawing
w <- raster(paste0(twd, "/Origin_00.tif"))
w[w < 20 | w > 40] <- 0
w[w != 0] <- 1

W_00 <- raster(paste0(twd, "/WUI_00.tif"))
W_10 <- raster(paste0(twd, "/WUI_10.tif"))
W_20 <- raster(paste0(twd, "/WUI_20.tif"))
delta <- 4*W_20 + 2*W_10 + W_00
c <- delta - 10 * w
d <- c
d[c==0] <- NA
d[c==-10] <- 10
d[c==1|c==-9] <- 1
d[c==2|c==-8] <- 2
d[c==4|c==-6] <- 3
d[c==3|c==-7] <- 4
d[c==5|c==-5] <- 5
d[c==6|c==-4] <- 6
d[c==7|c==-3] <- 7
dc <- crop(d, extent(27.2, 27.4, -25.7, -25.6))
df_d <- as.data.frame(dc, xy = T)
names(df_d) <- c("x", "y", "LC")

myLocation <- c(27, -26, 27.4, -25.5)
myMap <- get_stadiamap(bbox = myLocation, zoom = 13, maptype = "stamen_terrain_background", crop = FALSE)
city <- cbind(-25.6532131428673, 27.25591543700737, 'Rustenburg') %>%
  as.data.frame()
names(city) <- c('y', 'x', 'name')
city$x <- as.double(city$x)
city$y <- as.double(city$y)

p2 <- ggmap(myMap) +
  geom_point(data = df_d, aes(x = x, y = y, color = as.character(LC)), size = 0.5) +
  geom_point(data = city, mapping = aes(x = x, y = y), color = 'black', fill = 'red', shape = 21, size = 1, stroke = 0.5) + 
  geom_text_repel(data = city, mapping = aes(x = x, y = y, label = name), color = 'white', size = 3, bg.color = "black", nudge_y = 0.007, nudge_x = 0.001) +
  scale_color_manual(name = "",
                     values = LCcolors,
                     labels = LCnames,
                     na.translate = FALSE,
                     guide = 'none') +
  theme_bw() +
  theme(
        plot.background = element_rect(color = "transparent", fill ="transparent"),
        plot.margin = margin(2,2,2,2),
        legend.background = element_rect(color = "transparent", fill ="transparent"),
        axis.text = element_text(size = 6), 
        axis.text.y = element_text(angle = 90, hjust = 0.5)) +
  scale_x_continuous(expand = c(0,0), breaks = c(27.25, 27.35), label = c('27.25°E', '27.35°E'), limits = c(27.3, 27.4)) +
  scale_y_continuous(expand = c(0,0), breaks = c(-25.68, -25.63), label = c('25.68°S', '25.63°S'), limits = c(-25.7, -25.6)) +
  labs(x ="", y = "", fill = '') +
  guides(fill = "none")

# Pearl river delta extent(114.4,114.6,22.55,22.65)
i <- 500
twd <- paste0(idir, "/Data/fig3/temp", i)

# drawing
w <- raster(paste0(twd, "/Origin_00.tif"))
w[w < 20 | w > 40] <- 0
w[w != 0] <- 1

W_00 <- raster(paste0(twd, "/WUI_00.tif"))
W_10 <- raster(paste0(twd, "/WUI_10.tif"))
W_20 <- raster(paste0(twd, "/WUI_20.tif"))
delta <- 4*W_20 + 2*W_10 + W_00
c <- delta - 10 * w
d <- c
d[c==0] <- NA
d[c==-10] <- 10
d[c==1|c==-9] <- 1
d[c==2|c==-8] <- 2
d[c==4|c==-6] <- 3
d[c==3|c==-7] <- 4
d[c==5|c==-5] <- 5
d[c==6|c==-4] <- 6
d[c==7|c==-3] <- 7
dc <- crop(d, extent(114.4,114.6,22.55,22.65))
df_d <- as.data.frame(dc, xy = T)
names(df_d) <- c("x", "y", "LC")

myLocation <- c(114.4, 22.55, 114.6, 22.65)
myMap <- get_stadiamap(bbox = myLocation, zoom = 13, maptype = "stamen_terrain_background", crop = FALSE)
city <- cbind(22.599007134034593, 114.53970578303922, 'Dakeng') %>%
  as.data.frame()
names(city) <- c('y', 'x', 'name')
city$x <- as.double(city$x)
city$y <- as.double(city$y)

p3 <- ggmap(myMap) +
    geom_point(data = df_d, aes(x = x, y = y, color = as.character(LC)), size = 0.5) +
  geom_point(data = city, mapping = aes(x = x, y = y), color = 'black', fill = 'red', shape = 21, size = 1, stroke = 0.5) + 
  geom_text_repel(data = city, mapping = aes(x = x, y = y, label = name), color = 'white', size = 3, bg.color = "black", nudge_y = 0.007, nudge_x = 0.001) +
    scale_color_manual(name = "",
                       values = LCcolors,
                       labels = LCnames,
                       na.translate = FALSE,
                       guide = 'none') +
    theme_bw() +
    theme(
        plot.background = element_rect(color = "transparent", fill ="transparent"),
        plot.margin = margin(2,2,2,2),
        legend.background = element_rect(color = "transparent", fill ="transparent"),
        axis.text = element_text(size = 6), 
        axis.text.y = element_text(angle = 90, hjust = 0.5)) +
    scale_x_continuous(expand = c(0,0), breaks = c(114.45, 114.55), label = c('114.45°E', '114.55°E'), limits = c(114.4, 114.5)) +
    scale_y_continuous(expand = c(0,0), breaks = c(22.62, 22.57), label = c('22.62°N', '22.57°N'), limits = c(22.55, 22.65)) +
    labs(x ="", y = "", fill = '') + 
    guides(fill = "none")

odir <- paste0(idir, "Figure")
ggsave(plot = p1,
       filename = "fig3_local_EUS.pdf",
       device = "pdf", path = odir,
       width = 70, height = 50, units = "mm",
       dpi = 320)
ggsave(plot = p2,
       filename = "fig3_local_SAfrica.pdf",
       device = "pdf", path = odir,
       width = 70, height = 50, units = "mm",
       dpi = 320)
ggsave(plot = p3,
       filename = "fig3_local_CA.pdf",
       device = "pdf", path = odir,
       width = 70, height = 50, units = "mm",
       dpi = 320)
```

## draw static graph (2000-2010, 2010-2020)
```{r}
df <- NULL

d1 <- rList[[2]] - rList[[1]]
d1 <- aggregate(d1, fact = c(10, 10))
d1[d1 == 0] <- NA
df[[1]] <- as.data.frame(d1, xy=T) %>% 
  dplyr::mutate(type = '2000-2010') %>%
  filter(!is.na(layer))

d2 <- rList[[3]] - rList[[2]]
d2 <- aggregate(d2, fact = c(10, 10))
d2[d2 == 0] <- NA
df[[2]] <- as.data.frame(d2, xy=T) %>% 
  dplyr::mutate(type = '2010-2020') %>%
  filter(!is.na(layer))

delta <- aggregate(delta, fact = c(10, 10))
delta[delta == 0] <- NA
df[[3]] <- as.data.frame(delta, xy=T) %>% 
  dplyr::mutate(type = '2000-2020') %>%
  filter(!is.na(layer))
names(df[[3]]) <- names(df[[1]])

dfb <- dplyr::bind_rows(df)

a <- ggdensity(dfb, x = "layer", xlab = F, ylab = F, rug = F, 
          color = "type", fill = "type", adjust = 3, alpha = 0.3, size = 0.1,
          palette = c("#00AFBB", "#FC4E07", "#E7B800")) +
    scale_x_continuous(limits = c(-0.02, 0.02), labels = percent, expand = c(0,0)) + 
    scale_y_continuous() + 
    coord_fixed(ratio = 0.00004) +
    theme(
        legend.title = element_blank(), 
        legend.position = "none", 
        legend.text = element_text(size = 6), 
        legend.key.size = unit(0.2, 'in'),
        legend.direction = "vertical",
        axis.line.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        axis.line.x = element_blank(), 
        axis.text.x = element_blank(), 
        axis.ticks.x = element_blank()) + 
    labs(x = "", y = "")

b <- ggplot(dfb) +
    geom_boxplot(aes(x = layer, y = factor(type, levels = c('2000-2010', '2010-2020', '2000-2020')), lwd = 0.1,
                     color = factor(type, levels = c('2000-2010', '2010-2020', '2000-2020'))),lwd = 0.1, outlier.size = 0.001) +
    scale_x_continuous(limits = c(-0.02, 0.02), breaks = c(-0.01, 0, 0.01), labels = c('-1%', '0', '1%'), expand = c(0,0)) +
    scale_y_discrete(position = "right") +
    scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07"), labels = c('2000-2010', '2010-2020', '2000-2020')) +
    theme_classic() +
    theme(aspect.ratio = 0.7,
          legend.title = element_blank(),
          legend.position = 'none', 
          legend.text = element_text(size = 6), 
          axis.text = element_text(size = 6), 
          axis.title = element_text(size = 6),
          axis.line.y = element_blank(), 
          axis.title.y = element_blank(), 
          axis.ticks.y = element_blank()) + 
    labs(x = expression(Delta(WUI) ~ "(%)"), y = '') 
  
p <- a + b + plot_layout(ncol = 1)

odir <-paste0(idir, "Figure")

ggsave(plot = p,
       filename = "fig3_density.pdf",
       device = "pdf", path = odir,
       width = 40, height = 50, units = "mm",
       dpi = 320)
```